'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.WebService1Soap")>  _
    Public Interface WebService1Soap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Restar", ReplyAction:="*")>  _
        Function Restar(ByVal num1 As Double, ByVal num2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Restar", ReplyAction:="*")>  _
        Function RestarAsync(ByVal num1 As Double, ByVal num2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SumaOperaciones", ReplyAction:="*")>  _
        Function SumaOperaciones(ByVal nro1 As Double, ByVal nro2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SumaOperaciones", ReplyAction:="*")>  _
        Function SumaOperacionesAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Raiz", ReplyAction:="*")>  _
        Function Raiz(ByVal n As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Raiz", ReplyAction:="*")>  _
        Function RaizAsync(ByVal n As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PotenciaOperaciones", ReplyAction:="*")>  _
        Function PotenciaOperaciones(ByVal base1 As Double, ByVal exp As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PotenciaOperaciones", ReplyAction:="*")>  _
        Function PotenciaOperacionesAsync(ByVal base1 As Double, ByVal exp As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/logaritmo", ReplyAction:="*")>  _
        Function logaritmo(ByVal n As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/logaritmo", ReplyAction:="*")>  _
        Function logaritmoAsync(ByVal n As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/factorial", ReplyAction:="*")>  _
        Function factorial(ByVal n As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/factorial", ReplyAction:="*")>  _
        Function factorialAsync(ByVal n As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/dividir", ReplyAction:="*")>  _
        Function dividir(ByVal num1 As Double, ByVal num2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/dividir", ReplyAction:="*")>  _
        Function dividirAsync(ByVal num1 As Double, ByVal num2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/porcentaje", ReplyAction:="*")>  _
        Function porcentaje(ByVal num1 As Double, ByVal num2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/porcentaje", ReplyAction:="*")>  _
        Function porcentajeAsync(ByVal num1 As Double, ByVal num2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/multiplicacion", ReplyAction:="*")>  _
        Function multiplicacion(ByVal num1 As Double, ByVal num2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/multiplicacion", ReplyAction:="*")>  _
        Function multiplicacionAsync(ByVal num1 As Double, ByVal num2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/vabsoluto", ReplyAction:="*")>  _
        Function vabsoluto(ByVal n As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/vabsoluto", ReplyAction:="*")>  _
        Function vabsolutoAsync(ByVal n As Double) As System.Threading.Tasks.Task(Of Double)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebService1SoapChannel
        Inherits ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebService1SoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.WebService1Soap)
        Implements ServiceReference1.WebService1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Restar(ByVal num1 As Double, ByVal num2 As Double) As Double Implements ServiceReference1.WebService1Soap.Restar
            Return MyBase.Channel.Restar(num1, num2)
        End Function
        
        Public Function RestarAsync(ByVal num1 As Double, ByVal num2 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.RestarAsync
            Return MyBase.Channel.RestarAsync(num1, num2)
        End Function
        
        Public Function SumaOperaciones(ByVal nro1 As Double, ByVal nro2 As Double) As Double Implements ServiceReference1.WebService1Soap.SumaOperaciones
            Return MyBase.Channel.SumaOperaciones(nro1, nro2)
        End Function
        
        Public Function SumaOperacionesAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.SumaOperacionesAsync
            Return MyBase.Channel.SumaOperacionesAsync(nro1, nro2)
        End Function
        
        Public Function Raiz(ByVal n As Double) As Double Implements ServiceReference1.WebService1Soap.Raiz
            Return MyBase.Channel.Raiz(n)
        End Function
        
        Public Function RaizAsync(ByVal n As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.RaizAsync
            Return MyBase.Channel.RaizAsync(n)
        End Function
        
        Public Function PotenciaOperaciones(ByVal base1 As Double, ByVal exp As Double) As Double Implements ServiceReference1.WebService1Soap.PotenciaOperaciones
            Return MyBase.Channel.PotenciaOperaciones(base1, exp)
        End Function
        
        Public Function PotenciaOperacionesAsync(ByVal base1 As Double, ByVal exp As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.PotenciaOperacionesAsync
            Return MyBase.Channel.PotenciaOperacionesAsync(base1, exp)
        End Function
        
        Public Function logaritmo(ByVal n As Double) As Double Implements ServiceReference1.WebService1Soap.logaritmo
            Return MyBase.Channel.logaritmo(n)
        End Function
        
        Public Function logaritmoAsync(ByVal n As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.logaritmoAsync
            Return MyBase.Channel.logaritmoAsync(n)
        End Function
        
        Public Function factorial(ByVal n As Double) As Double Implements ServiceReference1.WebService1Soap.factorial
            Return MyBase.Channel.factorial(n)
        End Function
        
        Public Function factorialAsync(ByVal n As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.factorialAsync
            Return MyBase.Channel.factorialAsync(n)
        End Function
        
        Public Function dividir(ByVal num1 As Double, ByVal num2 As Double) As Double Implements ServiceReference1.WebService1Soap.dividir
            Return MyBase.Channel.dividir(num1, num2)
        End Function
        
        Public Function dividirAsync(ByVal num1 As Double, ByVal num2 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.dividirAsync
            Return MyBase.Channel.dividirAsync(num1, num2)
        End Function
        
        Public Function porcentaje(ByVal num1 As Double, ByVal num2 As Double) As Double Implements ServiceReference1.WebService1Soap.porcentaje
            Return MyBase.Channel.porcentaje(num1, num2)
        End Function
        
        Public Function porcentajeAsync(ByVal num1 As Double, ByVal num2 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.porcentajeAsync
            Return MyBase.Channel.porcentajeAsync(num1, num2)
        End Function
        
        Public Function multiplicacion(ByVal num1 As Double, ByVal num2 As Double) As Double Implements ServiceReference1.WebService1Soap.multiplicacion
            Return MyBase.Channel.multiplicacion(num1, num2)
        End Function
        
        Public Function multiplicacionAsync(ByVal num1 As Double, ByVal num2 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.multiplicacionAsync
            Return MyBase.Channel.multiplicacionAsync(num1, num2)
        End Function
        
        Public Function vabsoluto(ByVal n As Double) As Double Implements ServiceReference1.WebService1Soap.vabsoluto
            Return MyBase.Channel.vabsoluto(n)
        End Function
        
        Public Function vabsolutoAsync(ByVal n As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.vabsolutoAsync
            Return MyBase.Channel.vabsolutoAsync(n)
        End Function
    End Class
End Namespace
